import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';

const scryptAsync = promisify(scrypt);

/**
 * Hashes a plaintext password using scrypt
 * @param {string} password - The plaintext password to hash
 * @returns {Promise<string>} A promise resolving to the salted password hash
 */
export const hash = async (password) => {
  const salt = randomBytes(8).toString('hex');
  const derivedKey = await scryptAsync(password, salt, 64);

  return `${salt}:${derivedKey.toString('hex')}`;
};

/**
 * Verifies a plaintext password against a previously generated password hash
 * @param {string} password - The plaintext password to verify
 * @param {string} storedHash - The hash previously generated by {@link hash}
 * @returns {Promise<boolean>} Whether the password matches the stored hash
 */
export const verify = async (password, storedHash) => {
  const [salt, key] = storedHash.split(':');
  const derivedKey = await scryptAsync(password, salt, 64);

  return timingSafeEqual(Buffer.from(key, 'hex'), derivedKey);
};